# Generated by Django 5.2.6 on 2025-09-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.IntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.IntegerField()),
                ('shift', models.CharField(choices=[('day', 'Day'), ('evening', 'Evening')], max_length=50)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], max_length=50)),
                ('fat', models.FloatField()),
                ('qnt', models.FloatField()),
                ('amt', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_app.customer')),
            ],
        ),
    ]
