# Generated by Django 5.2.6 on 2025-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='acc_no',
            field=models.IntegerField(blank=True),
        ),
    ]
