# Generated by Django 5.2.6 on 2025-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0002_alter_milkentry_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='acc_no',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
