# Generated by Django 5.2.6 on 2025-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0003_alter_milkentry_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='shift',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'Evening')], max_length=50),
        ),
    ]
